name: Tests Workflow

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  issues: read
  checks: write
  pull-requests: write
  pages: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: ⚙ Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x spotlessCheck -x test

      - name: Check Code Format
        run: ./gradlew spotlessCheck

      - name: Clean Allure Results
        run: ./gradlew cleanAllureResults

      - name: Run API Tests
        run: ./gradlew apiTests

      - name: Publish Test Results
        if: (!cancelled())
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: "API Smoke Test Results (${{ github.event.workflow_run.event || github.event_name }})"
          files: "**/build/test-results/**/TEST-*.xml"

      - name: Collect Allure Results
        if: always()
        run: |
          mkdir -p build/allure-results
          find . -path "*/build/allure-results" -type d -not -path "./build/allure-results" | while read dir; do
            cp -r "$dir"/* build/allure-results/ || true
          done

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history/${{ github.ref_name }}
          force_orphan: true

